/**
 * scripts/seed/seed-decks.ts
 *
 * Reads YAML deck specs in `scripts/seed/decks/`, derives stable UUIDv5
 * identifiers, and writes `supabase/migrations/0009_seed_bundled_decks.sql`
 * with idempotent ON CONFLICT upserts.
 *
 * Run via: `pnpm seed:decks`
 *
 * NEVER rename a deck's `id` slug or reorder a deck's cards — both inputs
 * feed into the deterministic UUIDv5 derivation, and changing them re-rolls
 * the UUIDs (orphaning any FKs in `reviews`).
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { v5 as uuidv5 } from 'uuid';

// Fixed namespace UUID for Repeaty bundled decks. Generated once via uuidv4
// and pinned here. NEVER change — every existing card UUID depends on it.
const REPEATY_DECKS_NAMESPACE = '8e1b3a4a-7f71-4f9b-b1d8-3b2c1a0d9e7c';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const DECKS_DIR = join(__dirname, 'decks');
const MIGRATION_PATH = join(REPO_ROOT, 'supabase', 'migrations', '0009_seed_bundled_decks.sql');

const CEFR_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'] as const;
type CefrLevel = (typeof CEFR_LEVELS)[number];

export type DeckSpec = {
  id: string;
  name: string;
  language_code: string;
  cefr_level: CefrLevel;
  cards: ReadonlyArray<{
    target: string;
    native: string;
    ipa?: string;
    example_target?: string;
    example_native?: string;
  }>;
};

export const deckUuid = (slug: string): string => uuidv5(slug, REPEATY_DECKS_NAMESPACE);
export const cardUuid = (deckSlug: string, index: number): string =>
  uuidv5(`${deckSlug}/${index}`, REPEATY_DECKS_NAMESPACE);

function sqlString(value: string | undefined | null): string {
  if (value === undefined || value === null) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function isCefrLevel(value: unknown): value is CefrLevel {
  return typeof value === 'string' && (CEFR_LEVELS as readonly string[]).includes(value);
}

function validateSpec(spec: unknown, source: string): asserts spec is DeckSpec {
  if (!spec || typeof spec !== 'object') {
    throw new Error(`${source}: top-level value must be an object`);
  }
  const s = spec as Record<string, unknown>;
  if (typeof s.id !== 'string' || s.id.length === 0) {
    throw new Error(`${source}: id must be a non-empty string`);
  }
  if (typeof s.name !== 'string' || s.name.length === 0) {
    throw new Error(`${source}: name must be a non-empty string`);
  }
  if (typeof s.language_code !== 'string' || s.language_code.length === 0) {
    throw new Error(`${source}: language_code must be a non-empty string`);
  }
  if (!isCefrLevel(s.cefr_level)) {
    throw new Error(`${source}: cefr_level must be one of A1..C2`);
  }
  if (!Array.isArray(s.cards)) {
    throw new Error(`${source}: cards must be an array`);
  }
  s.cards.forEach((card, idx) => {
    const c = card as Record<string, unknown>;
    if (typeof c.target !== 'string' || c.target.length === 0) {
      throw new Error(`${source} card[${idx}]: target must be a non-empty string`);
    }
    if (typeof c.native !== 'string' || c.native.length === 0) {
      throw new Error(`${source} card[${idx}]: native must be a non-empty string`);
    }
  });
}

export async function loadDeckSpecs(decksDir: string): Promise<DeckSpec[]> {
  const entries = readdirSync(decksDir).filter(
    (f) => f.endsWith('.yaml') || f.endsWith('.yml'),
  );
  entries.sort(); // stable order across filesystems
  const specs: DeckSpec[] = [];
  for (const filename of entries) {
    const filepath = join(decksDir, filename);
    const raw = readFileSync(filepath, 'utf-8');
    const parsed = yaml.load(raw);
    validateSpec(parsed, filename);
    if (parsed.cards.length === 0) {
      console.warn(`${filename}: 0 cards — skipping (placeholder).`);
      continue;
    }
    specs.push(parsed);
  }
  return specs;
}

export function generateMigrationSql(specs: ReadonlyArray<DeckSpec>): string {
  const lines: string[] = [];
  lines.push('-- 0009_seed_bundled_decks.sql');
  lines.push('-- AUTO-GENERATED by scripts/seed/seed-decks.ts. DO NOT EDIT BY HAND.');
  lines.push('-- Edit scripts/seed/decks/*.yaml and run `pnpm seed:decks`.');
  lines.push('-- See scripts/seed/README.md for the workflow + idempotency rules.');
  lines.push('');

  const sortedSpecs = [...specs].sort((a, b) => a.id.localeCompare(b.id));

  for (const spec of sortedSpecs) {
    const dId = deckUuid(spec.id);
    lines.push(`-- ──── ${spec.name} (${spec.language_code} · ${spec.cefr_level}) ────`);
    lines.push(`insert into public.decks (id, name, language_code, cefr_level, source, owner_id)`);
    lines.push(
      `values (${sqlString(dId)}, ${sqlString(spec.name)}, ${sqlString(spec.language_code)}, ${sqlString(spec.cefr_level)}, 'bundled', null)`,
    );
    lines.push(`on conflict (id) do update set`);
    lines.push(`  name = excluded.name,`);
    lines.push(`  language_code = excluded.language_code,`);
    lines.push(`  cefr_level = excluded.cefr_level;`);
    lines.push('');

    spec.cards.forEach((card, idx) => {
      const cId = cardUuid(spec.id, idx);
      lines.push(
        `insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)`,
      );
      lines.push(
        `values (${sqlString(cId)}, ${sqlString(dId)}, ${sqlString(card.target)}, ${sqlString(card.native)}, ${sqlString(card.ipa)}, ${sqlString(card.example_target)}, ${sqlString(card.example_native)}, ${sqlString(spec.language_code)})`,
      );
      lines.push(`on conflict (id) do update set`);
      lines.push(`  target_text = excluded.target_text,`);
      lines.push(`  native_text = excluded.native_text,`);
      lines.push(`  ipa = excluded.ipa,`);
      lines.push(`  example_sentence_target = excluded.example_sentence_target,`);
      lines.push(`  example_sentence_native = excluded.example_sentence_native,`);
      lines.push(`  language_code = excluded.language_code;`);
    });
    lines.push('');
  }

  return lines.join('\n');
}

async function main(): Promise<void> {
  const specs = await loadDeckSpecs(DECKS_DIR);
  const sql = generateMigrationSql(specs);
  writeFileSync(MIGRATION_PATH, sql);
  const totalCards = specs.reduce((sum, s) => sum + s.cards.length, 0);
  console.log(
    `✓ wrote ${MIGRATION_PATH}\n  ${specs.length} deck(s), ${totalCards} card(s)`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  void main();
}
