-- 0009_seed_bundled_decks.sql
-- AUTO-GENERATED by scripts/seed/seed-decks.ts. DO NOT EDIT BY HAND.
-- Edit scripts/seed/decks/*.yaml and run `pnpm seed:decks`.
-- See scripts/seed/README.md for the workflow + idempotency rules.

-- ──── Spanish — Starter (A1) (es · A1) ────
insert into public.decks (id, name, language_code, cefr_level, source, owner_id)
values ('5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'Spanish — Starter (A1)', 'es', 'A1', 'bundled', null)
on conflict (id) do update set
  name = excluded.name,
  language_code = excluded.language_code,
  cefr_level = excluded.cefr_level;

insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('8b9da4f9-aed7-58d3-9fad-67004f92d806', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'hola', 'hello', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('b0e4c4e5-2afb-5582-b40a-32e6555f48f0', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'buenos días', 'good morning', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('2748b63e-11b5-5b1c-8426-ed5feb8cc2ec', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'buenas tardes', 'good afternoon', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('0c763e7e-0a46-574b-b454-ce72505f3c85', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'buenas noches', 'good evening', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('59350d68-4c2e-515b-806e-1b65574aaf81', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'adiós', 'goodbye', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('f0c9f0a9-dec0-5ca7-9396-0e80d25ec34e', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'hasta luego', 'see you later', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('d61b752d-bc6b-5543-a103-cc7ac2adc417', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'sí', 'yes', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('f4952336-0221-56e8-8118-cf11eff56061', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'no', 'no', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('515e9032-5dc3-5535-b070-ce677dafd0a9', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'gracias', 'thank you', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('5bad514b-4503-5a9d-9589-467e747fadf9', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'de nada', 'you''re welcome', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('7d79cd32-5b7e-5821-a32b-f2ed090eab92', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'por favor', 'please', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('faf1bb77-846b-5886-b5dd-3a85d22c99e7', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'uno', 'one', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('0b7c5011-aca8-5e14-b07d-a3f331132145', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'dos', 'two', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('4e03741e-f80b-5c99-845b-f8987a29e603', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'tres', 'three', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('5460c099-0956-5770-a35c-91d863b67210', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'cuatro', 'four', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('45dfced3-aacc-5951-95c8-7cec1dbb3d95', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'cinco', 'five', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('dd7cc876-ea27-5df3-a188-97abb4389a5e', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'seis', 'six', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('c990d431-08e7-5036-860a-6e4516276466', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'siete', 'seven', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('f085cbf9-163c-5d41-9380-af56f5803fcd', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'ocho', 'eight', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('1644a4b2-38e3-5973-aa9f-2141632d59bc', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'nueve', 'nine', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('e5b81d19-240f-5678-9515-e658701fa006', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'diez', 'ten', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('4d8d67c5-3d4e-5eb1-8122-61b19b693310', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'lunes', 'Monday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('004d9ce7-26d5-5b00-b3e7-534f994f1b62', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'martes', 'Tuesday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('efe9d4bb-210c-53a2-bf91-fb5f319b0293', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'miércoles', 'Wednesday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('5428e494-1f32-5f05-a1ef-844d179911cb', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'jueves', 'Thursday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('6e7b4b8e-da04-5a4d-8db5-2a3b3245e38a', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'viernes', 'Friday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('0a73c934-6763-5fed-8566-aabcd8d903af', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'sábado', 'Saturday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('5b007257-ba78-53c8-b606-6d328005130a', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'domingo', 'Sunday', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('10e7ca94-2f0f-5add-969f-cc866e36b380', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'rojo', 'red', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('980ea436-a85d-51cb-b0c1-848f4066fc1b', '5b13ed77-a9ed-5567-abc3-9674c5589fd2', 'azul', 'blue', null, null, null, 'es')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;

-- ──── French — Starter (A1) (fr · A1) ────
insert into public.decks (id, name, language_code, cefr_level, source, owner_id)
values ('fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'French — Starter (A1)', 'fr', 'A1', 'bundled', null)
on conflict (id) do update set
  name = excluded.name,
  language_code = excluded.language_code,
  cefr_level = excluded.cefr_level;

insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('7e37cbe5-2f63-59a2-a109-c4e5e2d17659', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'bonjour', 'hello', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('dacd7e81-a7f7-5f1e-95c3-6b90d20e9ef0', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'bonsoir', 'good evening', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('f3bc2220-3fe3-5dc7-8b04-6c6ad715815a', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'salut', 'hi (casual)', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('8e1da540-9f57-50cc-aa64-e762d935633a', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'au revoir', 'goodbye', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('148114aa-6198-57fe-9602-c696decccb06', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'à bientôt', 'see you soon', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('a4ac4b4f-9cdc-5bcc-901a-e65287ebcda3', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'oui', 'yes', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('29710aed-1b7e-5d0f-bd0a-78390ad1191e', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'non', 'no', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('08a08771-4dc0-585c-8fbd-fdd1a65c1b94', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'merci', 'thank you', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('c9a20584-9938-5b20-88c5-e3c0dd3efdcf', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'de rien', 'you''re welcome', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('1d573b4c-9016-5f4c-8abd-6ed61bea6cce', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 's''il vous plaît', 'please (formal)', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('f7ba79de-d168-5108-ad72-96ec414820d1', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'excusez-moi', 'excuse me', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('fe7e9b79-ab04-5fd6-ace6-87055c3b0e76', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'un', 'one', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('a43cb224-7bc9-5dc1-bad8-e01ffbda33b1', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'deux', 'two', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('8ee5db83-db83-5f90-b0a0-9d664d8dabde', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'trois', 'three', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('8412ccb1-4b66-56d6-925d-d3d215a2fe95', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'quatre', 'four', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('456447ae-f31d-5aa5-a0af-b0ff62641fb0', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'cinq', 'five', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('21d6e4d2-78a0-53ec-815b-172b5c8cd6a7', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'six', 'six', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('c4193c27-d860-5850-ae04-bf9870c4dd3f', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'sept', 'seven', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('d9d66d7b-7912-5c11-9261-2e728da3740e', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'huit', 'eight', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('7b70e8e3-ddcf-5c44-b9d5-d0f1dd17216c', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'neuf', 'nine', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('cf4797ba-207e-5ca0-a8e6-ab2ee04257b5', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'dix', 'ten', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('f8a0e1cc-6557-5c7c-bf96-cbbeed30a5af', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'lundi', 'Monday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('621a19aa-7aab-5cdd-aa61-b9dff79723b9', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'mardi', 'Tuesday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('dc2ada4f-4d2a-54f3-985e-b1bd09edcb4a', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'mercredi', 'Wednesday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('8482b237-49ef-57df-ada2-2739bf1f535c', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'jeudi', 'Thursday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('66f46d48-f409-59f0-990f-d0d7ef7e9f6a', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'vendredi', 'Friday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('311b183b-5c06-59d7-b0d7-5b392bd9d069', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'samedi', 'Saturday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('0a12e6f7-03db-5bde-8dcf-43dd51b852af', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'dimanche', 'Sunday', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('1ed2fbd8-e443-54db-a470-e1d080f96b8a', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'rouge', 'red', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
insert into public.cards (id, deck_id, target_text, native_text, ipa, example_sentence_target, example_sentence_native, language_code)
values ('2e8df498-fcaf-5bca-b06f-22feadf9d761', 'fd0d0d53-5f2b-5817-989b-a8bdd335ca2b', 'bleu', 'blue', null, null, null, 'fr')
on conflict (id) do update set
  target_text = excluded.target_text,
  native_text = excluded.native_text,
  ipa = excluded.ipa,
  example_sentence_target = excluded.example_sentence_target,
  example_sentence_native = excluded.example_sentence_native,
  language_code = excluded.language_code;
